/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package p5;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.geom.Arc2D;
import java.awt.geom.Area;
import java.awt.geom.CubicCurve2D;
import java.awt.geom.Ellipse2D;
import java.awt.geom.GeneralPath;
import java.awt.geom.QuadCurve2D;
import java.awt.geom.Rectangle2D;
import java.awt.geom.RoundRectangle2D;

/**
 *
 * @author daniel
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }
    
    @Override
    public void paint(Graphics g) {
        super.paint(g);
        Graphics2D g2d = (Graphics2D)g;
        //RoundRectangle2D rect = new RoundRectangle2D.Double(10.0,10.0,100.0,100.0,20.0,20.0);
        //g2d.draw(rect);
        /*
        Arc2D.Double arc = new Arc2D.Double(
                50, 50,     // Posición inicial (x, y) del arco
                200, 200,   // Ancho y alto del arco
                45, 270,    // Ángulo inicial y ángulo extendido
                Arc2D.OPEN   // Tipo de apertura del arco
        );
        g2d.draw(arc);
        */
        /*
        // Puntos de control y punto final de la curva cuadrática
        double x1 = 50, y1 = 100;    // Punto inicial
        double ctrlx = 150, ctrly = 20;  // Punto de control
        double x2 = 250, y2 = 100;    // Punto final

        // Crear una curva cuadrática
        QuadCurve2D curve = new QuadCurve2D.Double(x1, y1, ctrlx, ctrly, x2, y2);
        g2d.draw(curve);
        */
        /*
        // Puntos de control y punto final de la curva cúbica
        double x1 = 50, y1 = 100;    // Punto inicial
        double ctrlx1 = 100, ctrly1 = 20;  // Primer punto de control
        double ctrlx2 = 200, ctrly2 = 150; // Segundo punto de control
        double x2 = 250, y2 = 100;    // Punto final

        // Crear una curva cúbica
        CubicCurve2D curve = new CubicCurve2D.Double(x1, y1, ctrlx1, ctrly1, ctrlx2, ctrly2, x2, y2);
        g2d.draw(curve);
        */
        /*
        // Crear un objeto GeneralPath
        GeneralPath path = new GeneralPath();
        // Mover a la posición inicial
        path.moveTo(50, 50);
        // Dibujar una línea desde la posición inicial a la posición (150, 100)
        path.lineTo(150, 100);
        // Dibujar una línea desde la posición (150, 100) a la posición (250, 50)
        path.lineTo(250, 50);
        // Dibujar una línea desde la posición (250, 50) a la posición (200, 150)
        path.lineTo(200, 150);
        // Dibujar una línea desde la posición (200, 150) a la posición inicial (50, 50)
        path.closePath();
        g2d.draw(path);
        */
        // Crear formas geométricas individuales
        Rectangle2D rect = new Rectangle2D.Double(50, 50, 200, 100);
        Ellipse2D ellipse = new Ellipse2D.Double(100, 100, 200, 150);
        // Crear áreas para cada forma
        Area areaRect = new Area(rect);
        Area areaEllipse = new Area(ellipse);
        // Realizar una operación de unión para combinar las áreas
        areaRect.add(areaEllipse);
        g2d.draw(areaRect);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
