/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package practica4;

import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.Box;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.event.InternalFrameAdapter;
import javax.swing.filechooser.FileNameExtensionFilter;
import sm.dav.graficos.Lienzo2D;

/**
 *
 * @author daniel
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    private ManejadorVentanaInterna manejador;
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        setSize(960, 960);
        // 2) Creamos objeto manejador
        manejador = new ManejadorVentanaInterna();
    }

    private Lienzo2D getSelectedLienzo() {
        VentanaInterna vi;
        vi = (VentanaInterna) escritorio.getSelectedFrame();
        return vi != null ? vi.getLienzo2D() : null;
    }
    
    private void setAtributosSelectedLienzo(Lienzo2D l){
        if(l != null){
            this.Alisar.setSelected(l.isAlisar());
            this.Mover.setSelected(l.isMover());
            this.Transparencia.setSelected(l.isTransparencia());
            this.Relleno.setSelected(l.isRelleno());
            this.Paleta.setBackground(l.getColor());
            this.Grosor.setValue(l.getTrazo().hashCode());
            l.setTipo(Lienzo2D.posiblesTipos.LINEA);
            this.BotonLinea.setSelected(true);
        }
    }
    
    // 1) Definimos clase manejadora
    private class ManejadorVentanaInterna extends InternalFrameAdapter {
        public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            VentanaInterna vi = (VentanaInterna) evt.getInternalFrame();
            setAtributosSelectedLienzo(vi.getLienzo2D());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TipoDibujo = new javax.swing.ButtonGroup();
        jToolBar1 = new javax.swing.JToolBar();
        BotonLinea = new javax.swing.JToggleButton();
        BotonRectangulo = new javax.swing.JToggleButton();
        BotonElipse = new javax.swing.JToggleButton();
        Fantasma = new javax.swing.JToggleButton();
        Mover = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        Paleta = new javax.swing.JButton();
        Relleno = new javax.swing.JToggleButton();
        Transparencia = new javax.swing.JToggleButton();
        Alisar = new javax.swing.JToggleButton();
        Grosor = new javax.swing.JSlider();
        Volcar = new javax.swing.JButton();
        Estado = new javax.swing.JLabel();
        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Nuevo = new javax.swing.JMenuItem();
        Abrir = new javax.swing.JMenuItem();
        Guardar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PaintBásico");

        jToolBar1.setRollover(true);

        TipoDibujo.add(BotonLinea);
        BotonLinea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica4/linea.png"))); // NOI18N
        BotonLinea.setFocusable(false);
        BotonLinea.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonLinea.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotonLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonLineaActionPerformed(evt);
            }
        });
        jToolBar1.add(BotonLinea);

        TipoDibujo.add(BotonRectangulo);
        BotonRectangulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica4/rectangulo.png"))); // NOI18N
        BotonRectangulo.setFocusable(false);
        BotonRectangulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonRectangulo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotonRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRectanguloActionPerformed(evt);
            }
        });
        jToolBar1.add(BotonRectangulo);

        TipoDibujo.add(BotonElipse);
        BotonElipse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica4/elipse.png"))); // NOI18N
        BotonElipse.setFocusable(false);
        BotonElipse.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonElipse.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotonElipse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonElipseActionPerformed(evt);
            }
        });
        jToolBar1.add(BotonElipse);

        TipoDibujo.add(Fantasma);
        Fantasma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica4/fantasma.png"))); // NOI18N
        Fantasma.setFocusable(false);
        Fantasma.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Fantasma.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Fantasma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FantasmaActionPerformed(evt);
            }
        });
        jToolBar1.add(Fantasma);

        TipoDibujo.add(Mover);
        Mover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica4/seleccion.png"))); // NOI18N
        Mover.setFocusable(false);
        Mover.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Mover.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Mover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoverActionPerformed(evt);
            }
        });
        jToolBar1.add(Mover);

        jPanel1.setMaximumSize(new java.awt.Dimension(40, 40));
        jPanel1.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanel1.setLayout(new java.awt.BorderLayout());

        Paleta.setBackground(new java.awt.Color(0, 0, 0));
        Paleta.setForeground(new java.awt.Color(0, 0, 0));
        Paleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaletaActionPerformed(evt);
            }
        });
        jPanel1.add(Paleta, java.awt.BorderLayout.CENTER);

        jToolBar1.add(jPanel1);

        Relleno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica4/rellenar.png"))); // NOI18N
        Relleno.setFocusable(false);
        Relleno.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Relleno.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Relleno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RellenoActionPerformed(evt);
            }
        });
        jToolBar1.add(Relleno);

        Transparencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica4/transparencia.png"))); // NOI18N
        Transparencia.setFocusable(false);
        Transparencia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Transparencia.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Transparencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransparenciaActionPerformed(evt);
            }
        });
        jToolBar1.add(Transparencia);

        Alisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica4/alisar.png"))); // NOI18N
        Alisar.setFocusable(false);
        Alisar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Alisar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Alisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlisarActionPerformed(evt);
            }
        });
        jToolBar1.add(Alisar);

        Grosor.setMaximum(50);
        Grosor.setMinimum(1);
        Grosor.setValue(1);
        Grosor.setMaximumSize(new java.awt.Dimension(100, 16));
        Grosor.setPreferredSize(new java.awt.Dimension(100, 16));
        Grosor.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                GrosorStateChanged(evt);
            }
        });
        jToolBar1.add(Grosor);

        Volcar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica4/volcado.png"))); // NOI18N
        Volcar.setFocusable(false);
        Volcar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Volcar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Volcar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolcarActionPerformed(evt);
            }
        });
        jToolBar1.add(Volcar);

        Estado.setText("Barra de Estado");

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 462, Short.MAX_VALUE)
        );

        jMenu1.setText("Archivo");

        Nuevo.setText("Nuevo");
        Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoActionPerformed(evt);
            }
        });
        jMenu1.add(Nuevo);

        Abrir.setText("Abrir");
        Abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbrirActionPerformed(evt);
            }
        });
        jMenu1.add(Abrir);

        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });
        jMenu1.add(Guardar);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 775, Short.MAX_VALUE)
            .addComponent(Estado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(escritorio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Estado, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoActionPerformed
        BufferedImage img;
        JPanel panel = new JPanel();
        JTextField textField1 = new JTextField(5);
        JTextField textField2 = new JTextField(5);
        panel.add(new JLabel("Introducir Ancho:"));
        panel.add(textField1);
        panel.add(Box.createHorizontalStrut(15)); 
        panel.add(new JLabel("Introducir Alto:"));
        panel.add(textField2);
        int result = JOptionPane.showConfirmDialog(null, panel, "Ingrese el tamaño de la imagen",
        JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
        
        if(result == JOptionPane.OK_OPTION){
            try {
                int valor1 = Integer.parseInt(textField1.getText());
                int valor2 = Integer.parseInt(textField2.getText());
                img = new BufferedImage(valor1,valor2,BufferedImage.TYPE_INT_RGB);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Valores no válidos, se creará tamaño por defecto.", "Error", JOptionPane.ERROR_MESSAGE);
                img = new BufferedImage(400,400,BufferedImage.TYPE_INT_RGB);
            }
        } else {
            img = new BufferedImage(400,400,BufferedImage.TYPE_INT_RGB);
        }
        
        VentanaInterna vi = new VentanaInterna();
        escritorio.add(vi);
        vi.setVisible(true);
        setAtributosSelectedLienzo(vi.getLienzo2D());
        
        // 2) Enlazar generador con manejador
        vi.addInternalFrameListener(manejador);
        
        // Pintamos de blanco
        Graphics2D g2d = img.createGraphics();
        g2d.setColor(Color.WHITE);
        g2d.fillRect(0, 0, img.getWidth(), img.getHeight());
        g2d.dispose();
        
        vi.getLienzo2D().setImage(img);
    }//GEN-LAST:event_NuevoActionPerformed

    private void BotonLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonLineaActionPerformed
        Lienzo2D lienzo = getSelectedLienzo();
        if (lienzo != null) {
            lienzo.setMover(Mover.isSelected());
            lienzo.SalirModoEditar();
            lienzo.setTipo(Lienzo2D.posiblesTipos.LINEA);
            Estado.setText("Línea");
        }
    }//GEN-LAST:event_BotonLineaActionPerformed

    private void BotonRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRectanguloActionPerformed
        Lienzo2D lienzo = getSelectedLienzo();
        if (lienzo != null) {
            lienzo.setMover(Mover.isSelected());
            lienzo.SalirModoEditar();
            lienzo.setTipo(Lienzo2D.posiblesTipos.RECTANGULO);
            Estado.setText("Rectángulo");
        }
    }//GEN-LAST:event_BotonRectanguloActionPerformed

    private void BotonElipseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonElipseActionPerformed
        Lienzo2D lienzo = getSelectedLienzo();
        if (lienzo != null) {
            lienzo.setMover(Mover.isSelected());
            lienzo.SalirModoEditar();
            lienzo.setTipo(Lienzo2D.posiblesTipos.ELIPSE);
            Estado.setText("Elipse");
        }
    }//GEN-LAST:event_BotonElipseActionPerformed

    private void AbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbrirActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Imágenes", "jpg", "jpeg", "png", "gif", "bmp");
        fileChooser.setFileFilter(filter);
        int seleccion = fileChooser.showOpenDialog(this);
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            try {
                File f = fileChooser.getSelectedFile();
                BufferedImage img = ImageIO.read(f);
                VentanaInterna vi = new VentanaInterna();
                vi.getLienzo2D().setImage(img);
                vi.addInternalFrameListener(manejador);
                this.escritorio.add(vi);
                vi.setTitle(f.getName());
                vi.setVisible(true);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error al abrir la imagen: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_AbrirActionPerformed

    private String getFileExtension(File file) {
        String fileName = file.getName();
        int dotIndex = fileName.lastIndexOf('.');
        if (dotIndex > 0 && dotIndex < fileName.length() - 1) {
            return fileName.substring(dotIndex + 1).toLowerCase();
        }
        return "";
    }
 
    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        VentanaInterna vi = (VentanaInterna) escritorio.getSelectedFrame();
        if (vi != null) {
            BufferedImage img = vi.getLienzo2D().getPaintedImage();
            if (img != null) {
                JFileChooser dlg = new JFileChooser();
                FileNameExtensionFilter filter = new FileNameExtensionFilter("Imágenes", "jpg", "jpeg", "png", "gif", "bmp");
                dlg.setFileFilter(filter);
                int resp = dlg.showSaveDialog(this);
                if (resp == JFileChooser.APPROVE_OPTION) {
                    try {
                        File f = dlg.getSelectedFile();
                        String formato = getFileExtension(f);
                        if (formato == null || formato.isEmpty()) {
                            formato = "jpg";
                            f = new File(f.getAbsolutePath() + ".jpg");
                        }
                        ImageIO.write(img, formato, f);
                        vi.setTitle(f.getName());
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(this, "Error al guardar la imagen: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                        ex.printStackTrace();
                    }
                }
            }
        }
    }//GEN-LAST:event_GuardarActionPerformed

    private void FantasmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FantasmaActionPerformed
        Lienzo2D lienzo = getSelectedLienzo();
        if (lienzo != null) {
            lienzo.setTipo(Lienzo2D.posiblesTipos.FANTASMA);
            lienzo.SalirModoEditar();
            lienzo.setMover(Mover.isSelected());
            Estado.setText("Fantasma");
        }
    }//GEN-LAST:event_FantasmaActionPerformed

    private void RellenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RellenoActionPerformed
        Lienzo2D lienzo = getSelectedLienzo();
        if (lienzo != null) {
            lienzo.setRelleno(Relleno.isSelected());
        }
    }//GEN-LAST:event_RellenoActionPerformed

    private void MoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoverActionPerformed
        Lienzo2D lienzo = getSelectedLienzo();
        if (lienzo != null) {
            lienzo.setMover(Mover.isSelected());
        }
    }//GEN-LAST:event_MoverActionPerformed

    private void TransparenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransparenciaActionPerformed
        Lienzo2D lienzo = getSelectedLienzo();
        if (lienzo != null) {
            lienzo.setTransparencia(Transparencia.isSelected());
            // lienzo.repaint();
        }
    }//GEN-LAST:event_TransparenciaActionPerformed

    private void AlisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlisarActionPerformed
        Lienzo2D lienzo = getSelectedLienzo();
        if (lienzo != null) {
            lienzo.setAlisar(Alisar.isSelected());
            // lienzo.repaint();
        }
    }//GEN-LAST:event_AlisarActionPerformed

    private void GrosorStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_GrosorStateChanged
        Lienzo2D lienzo = getSelectedLienzo();
        if (lienzo != null) {
            lienzo.setTrazo((int) Grosor.getValue());
            // lienzo.repaint();
        }
    }//GEN-LAST:event_GrosorStateChanged

    private void PaletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaletaActionPerformed
        Color color = JColorChooser.showDialog(this, "Elije un color", Color.RED);
        Lienzo2D lienzo = getSelectedLienzo();
        if (lienzo != null) {
            lienzo.setColor(color);
            Paleta.setBackground(color);
        }

    }//GEN-LAST:event_PaletaActionPerformed

    private void VolcarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolcarActionPerformed
        Lienzo2D lienzo = getSelectedLienzo();
        if(lienzo != null) {
            lienzo.VolcarSeleccion();
        }
    }//GEN-LAST:event_VolcarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Abrir;
    private javax.swing.JToggleButton Alisar;
    private javax.swing.JToggleButton BotonElipse;
    private javax.swing.JToggleButton BotonLinea;
    private javax.swing.JToggleButton BotonRectangulo;
    private javax.swing.JLabel Estado;
    private javax.swing.JToggleButton Fantasma;
    private javax.swing.JSlider Grosor;
    private javax.swing.JMenuItem Guardar;
    private javax.swing.JToggleButton Mover;
    private javax.swing.JMenuItem Nuevo;
    private javax.swing.JButton Paleta;
    private javax.swing.JToggleButton Relleno;
    private javax.swing.ButtonGroup TipoDibujo;
    private javax.swing.JToggleButton Transparencia;
    private javax.swing.JButton Volcar;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
